Config:
  checkerTime: 10 #in ticks;
  debug-mode: false
  lore-format:
    - "{item-lore}"
    - ""
    - "&7Rarity: {rarity-prefix}"
  enable-glow: true
  inventory-blacklist:
    - "Example inventory title" #<- Inventory title here